spring.application.name=ongoinground
server.port=8081

amqp.exchange.name=round.topic

management.endpoints.web.exposure.include=health,info

spring.config.import=optional:consul:


spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500

round.client.host=http://resolver:8085

spring.security.oauth2.resourceserver.jwt.issuer-uri=http:8080/realms/micro2024

keycloak.realm=micro2024
keycloak.auth-server-url=http://localhost:8080
keycloak.resource=ongoinground
keycloak.credentials.secret:beUcfHL6BJ90dVhtYo1bo4UwzGs2hHkq
keycloak.principal-attribute=preferred_username