spring.application.name=resolver
server.port=8085

management.endpoints.web.exposure.include=health,info

spring.config.import=optional:consul:

spring.cloud.consul.enabled=false
spring.cloud.discovery.enabled=false
#spring.cloud.consul.host=consul
#spring.cloud.consul.port=8500

