input {
    file {
        path => "/var/log/resolver-service.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

filter {
    json {
        source => "message"
    }
}

output {
    elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "resolver-logs-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
}
