spring:
  application:
    name: recorder
  datasource:
    url: jdbc:h2:file:~/recorder;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  config:
    import:optional:consul:
    activate:
      on-profile: default
  cloud:
    consul:
      config:
        prefixes: "config"
        format: yaml
        default-context: "defaults"
        data-key: "application.yml"
      host: consul
      port: 8500
  rabbitmq:
    host: rabbitmq
    port: 5672

server:
  port: 8082

amqp:
  exchange:
    name: round.topic
  queue:
    won:
      name: outcome.won
    lost:
      name: outcome.lost
    name: outcome.all

management:
  endpoints:
    web:
      exposure:
        include: health

---

spring:
  application:
    name: recorder
  datasource:
    url: jdbc:h2:file:/data/recorder;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  config:
    import:optional:consul:
    activate:
      on-profile: docker
  cloud:
    consul:
      config:
        prefixes: "config"
        format: yaml
        default-context: "defaults"
        data-key: "application.yml"
      host: consul
      port: 8500
  rabbitmq:
    host: rabbitmq
    port: 5672

server:
  port: 8082

amqp:
  exchange:
    name: round.topic
  queue:
    won:
      name: outcome.won
    lost:
      name: outcome.lost
    name: outcome.all

management:
  endpoints:
    web:
      exposure:
        include: health
